### ISSUE TITLE
Conflict when trying to add secret in a capsule

### ISSUE THREAD

**Issue by Leouarz** [capsule-corp-ternoa/ternoa-enclaves#10]
Hello @peshwar9 @zorvan !!

A user from Secret Stash found an issue that was reproduced. When you : 
- Create a capsule
- Sync it correctly
- Try to add a secret in it
- Send the shards to the enclaves
- It yields a CONFLICT error

Is that a bug or a wanted feature ? Is it documented somewhere ?

Let me know if you need more details

![image](https://github.com/capsule-corp-ternoa/ternoa-enclaves/assets/15839293/52bf3501-633a-412c-be39-a63ba0cda2ed)

**Comment by zorvan** [comment]
Hello @Leouarz Thanks for your valuable feedback.

On the enclave side, base on the source-code, there is only single situation that returns "[CONFLICT (409)](https://github.com/capsule-corp-ternoa/ternoa-enclaves/blob/45c1c1a9c8af9aa0800a0e36dbba72384dc46f9c/src/chain/nft.rs#L367)", 
It is when someone wants to update a "secret-nft" keyshare which is not possible by definition. 

Are you sure that you are using the right API endpoint for updating the key (nft instead of capsule)?

**Comment by Leouarz** [comment]
Hey @zorvan,

Thanks for your quick feedback.
The NFT is this one : https://secret-stash.io/fr/nft/371652

I first created a capsule and it worked perfectly with the correct API to store capsule shards.

I then added a secret to it and got the conflict error. Probably because the enclaves have the Capsules shards.

You can see on the chain storage that the capsule is synced but not the secret. Also the chain does not contains any secret shards so the correct API should be to store the secret keys. That's where I get the conflict.

Also this must have happen recently because it was not like that before.

Pls telle me if you need more data.

**Comment by zorvan** [comment]
Agree. 
I found the cause. It's been changed recently and the fixed will be applied in our new deployment.

Thanks again.

**Comment by Leouarz** [comment]
Thank you very much, i'll wait for the release. Good luck !!
